---
files:
  (?x)^(
  .*/Makefile|
  .*\.sh|
  .*\.py|
  .*\.yaml|
  .*\.md
  )$
exclude:
  (?x)^(
  .*error.*\.yaml|
  experiments/.*|
  submodules/.*|
  kibot/PyPDF2/.*|
  kibot/PcbDraw/.*|
  tests/yaml_samples/simple_position_csv_pre.kibot.yaml
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
        args: [--unsafe]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: fix-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.23.0
    hooks:
      - id: yamllint
        args: [-c, .yamllint]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
