# Update the value_split example files

name: CI

# Controls when the workflow will run
on:
  push:
    paths:
    - 'value_split/value_split.kicad_sch'
    - 'value_split/resources.kibot.yaml'
    - '.github/workflows/update-value-split.yml'

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad7_auto_full:dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run KiBot
        run: |
          cd value_split
          kibot -c resources.kibot.yaml
          kibot -c value_split_replace.kibot.yaml
